general {
    hide_cursor = false
    no_fade_in = true
}

background {
    monitor = 
    path = screenshot
    blur_passes = 3
    blur_size = 10
}

label {
    monitor = eDP-1
    text = nothing to see here
    color = rgb(FFFFFF)
    font_size = 14
    font_family = Px437 ToshibaSat 8x14
    position = 0, 20
    halign = center
    valign = center
}

input-field {
    monitor = eDP-1
    size = 200, 30

    rounding = 0
    outline_thickness = 2
    outer_color = rgb(FFFFFF)
    inner_color = rgba(00000000)

    dots_size = 0.4
    dots_spacing = 0.2
    dots_center = true
    dots_rounding = 0
    dots_text_format = *

    font_color = rgb(FFFFFF)
    font_size = 14
    font_family = Px437 ToshibaSat 8x14

    placeholder_text =
    fail_text = wrong password
    fail_color = rgb(8F2133)
    
    position = 0, -20
    halign = center
    valign = center

    fade_on_empty = false
}

label {
    monitor = eDP-1
    text = cmd[update:500] lang="$(hyprctl devices -j | jq -r '.keyboards[] | select(.main) | .active_keymap')"; echo $(echo "$lang" |  tr '[:upper:]' '[:lower:]' )
    color = rgb(FFFFFF)
    font_size = 14
    font_family = Px437 ToshibaSat 8x14
    
    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = cmd[update:1000] echo "$(date +"%d.%m.%Y • %H:%M")"
    color = rgb(FFFFFF)

    font_size = 14
    font_family = Px437 ToshibaSat 8x14

    position = 0, -32
    halign = center
    valign = top
}

label {
    monitor = eDP-1
    text = cmd[update:60000] echo "$(cat /tmp/wttr.in.text)"
    color = rgb(FFFFFF)

    font_size = 14
    font_family = Px437 ToshibaSat 8x14

    position = 0, -56
    halign = center
    valign = top
}
